### ISSUE TITLE
Select broken on Firefox

### ISSUE THREAD

**Issue by tsargent** [namely/styleguide#280]
![screenshot 2016-04-11 14 10 24](https://cloud.githubusercontent.com/assets/173215/14437440/358862ea-ffef-11e5-8ff5-b728589c03d1.png)

might be related to this: https://www.dropbox.com/s/tlrr3iewl7gxbnl/Screenshot%202016-04-11%2014.10.24.png?dl=0

**Comment by loudhearted** [comment]
Task for reference: https://namely.atlassian.net/browse/EDF-415

**Comment by tsargent** [comment]
it looks like it's the `$white` that breaks it.  This seems to work:

```scss
select:-moz-focusring {
  color: transparent;
  text-shadow: 0 0 0 $grey-75;
}
```
