### ISSUE TITLE
hover rows on tables

### ISSUE THREAD

**Issue by tsargent** [namely/styleguide#282]
https://github.com/namely/styleguide/blob/develop/src/scss/base/_tables.scss#L46-L48

Should we change this:

```scss
tbody tr {
  &:hover {
    background-color: $grey-5;
  }
}
```

to something like this?

```scss
.hover-row {
   &:hover {
     background-color: $grey-5;
   }
}
```

The default functionality is indeed this hover change, but adding a utility might be safer, since this could easily change.
