### ISSUE TITLE
Document "states" utilities 

### ISSUE THREAD

**Issue by HipsterBrown** [namely/styleguide#89]
We have a set of css utility classes for common interaction states used around Namely, i.e `.hover-row`:

```scss
.hover-row:hover {
   background: $grey-5;
}
```

These should be documented on the Base page of the styleguide.
